### ISSUE TITLE
Bug in the audio only option

### ISSUE THREAD

**Issue by dmtzs** [dmtzs/DownYoutube#3]
There is a bug in the audio only option that appears like doesnt find a file. The error is the next one:
<br>
``Traceback (most recent call last):
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1884, in __call__
    return self.func(*args)
  File "D:\DownYoutube\DesktopApp\youtube.py", line 78, in DescargarVideo
    newFolderNameIn= VideoAudioConverter()
  File "D:\DownYoutube\DesktopApp\youtube.py", line 100, in VideoAudioConverter
    video= mp.VideoFileClip(newFolderNameIn)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado``

**Comment by dmtzs** [comment]
The problem is that in a development execution  ``python youtube.py`` the environment variable: IMAGEIO_FFMPEG_EXE cannot be established.

**Comment by dmtzs** [comment]
The environment variable: IMAGEIO_FFMPEG_EXE should be established only before the execution of the pyinstaller command so the executable will work fine and this is considered as production mode. If you want to execute in a development mode: ``python youtube.py`` then you need to delete the code line in which you try to established this environment variable. <br>
Another consideration about this is already in the README file.
We can consider this issue as fixed.
