### ISSUE TITLE
Bug when downloading with the option "Solo audio" selected

### ISSUE THREAD

**Issue by dmtzs** [dmtzs/DownYoutube#8]
In developer mode there is no problem but in production mode (exe file) there is an error when the program tries to convert the mp4 video to a mp3 format. This is an issue of the moviepy library, the error is the next one:
``
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "youtube.py", line 98, in DescargarVideo
  File "youtube.py", line 119, in VideoAudioConverter
  File "moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "moviepy\video\io\ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
  File "moviepy\video\io\ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
``

**Comment by dmtzs** [comment]
It look like we will need to import manually like before modifying the __init__.py file from video and audio respectively

**Comment by dmtzs** [comment]
This bug is caused because moviepy doesnt work good in an exe file, I should look for how the subprocess.py file is created because now now is where this library fails and the moment we create the onefile exe with pyinstaller

**Comment by dmtzs** [comment]
Added a wontfix label because the bug for pyinstaller cannot be fixed because the library doesnt work good with the onefile option of pyinstaller and with other exe libraries. I will change this if someday the library changes this problem.

**Comment by dmtzs** [comment]
I will try to do a test with the onedir flag of pyinstaller, maybe that could work but nothing is shure.

**Comment by dmtzs** [comment]
The problem is that the moviepy library doesnt work good when that library is required at the moment we build an exe file

**Comment by dmtzs** [comment]
This problem because its problem is from the same library will not have a fix until that library corrects that error. Meanwhile this issue will be open to let know this is happening today with the application and the label wontfix will be in the issue.
